spring.datasource.url=POSTGRES_DB_URL
spring.datasource.username=POSTGRES_USERNAME
spring.datasource.password=POSTGRES_PASSWORD

# 1 day and 7 days
application.security.jwt.secret-key=JWT_SECRET_KEY
application.security.jwt.expiration=JWT_TOKEN_EXPIRATION
application.security.jwt.refresh-token.expiration=JWT_REFRESH_TOKEN_EXPIRATION